name: Docs to PDF
on:
  push:
    branches:
      - main
    paths:
      - '**.md'
      - 'images/**'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      # Updated to v4 to fix the Node 20 deprecation warning
      - uses: actions/checkout@v4

      - name: Install PDF Generator
        run: npm i -g md-to-pdf

      - name: Build PDFs
        run: |
          # 1. Find all Markdown files and convert them to PDF
          find . -type f -name "*.md" -exec md-to-pdf {} \;
          
          # 2. Create the destination folder
          mkdir -p pdfs
          
          # 3. Find all generated PDFs and move them to the folder
          find . -type f -name "*.pdf" -exec mv {} pdfs/ \;

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: pdfs
