name: Docs to PDF
on:
  push:
    branches:
      - main
    paths:
      - '**.md'
      - 'images/**'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install md-to-pdf globally on the Ubuntu runner
      - name: Install PDF Generator
        run: npm i -g md-to-pdf

      # Run the tool and move PDFs to a dedicated folder
      - name: Build PDFs
        run: |
          md-to-pdf ./**/*.md
          mkdir -p pdfs
          mv ./**/*.pdf pdfs/

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: pdfs
